In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation || Every word in the sentence is represented as a vector of size voc_size
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[6609, 8463, 2300, 7127],
 [6609, 8463, 2300, 4544],
 [6609, 4987, 2300, 9414],
 [2171, 9455, 8535, 8480, 6446],
 [2171, 9455, 8535, 8480, 7413],
 [3405, 6609, 1642, 2300, 2072],
 [310, 8341, 7311, 8480]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8 ## max length of the sentence
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length) ## padding='pre' means add 0s at the beginning of the sentence
print(embedded_docs) 

[[   0    0    0    0 6609 8463 2300 7127]
 [   0    0    0    0 6609 8463 2300 4544]
 [   0    0    0    0 6609 4987 2300 9414]
 [   0    0    0 2171 9455 8535 8480 6446]
 [   0    0    0 2171 9455 8535 8480 7413]
 [   0    0    0 3405 6609 1642 2300 2072]
 [   0    0    0    0  310 8341 7311 8480]]


In [10]:
## feature representation
dim=10 ## dimension of the embedding vector

In [11]:
model=Sequential()## embedding layer is used to convert the one hot representation to word embedding representation
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

/Users/sanjayahirwar/Documents/THIS PC/CELL -Y/PROJECTS/SIMPLE_RNN/venv/lib/python3.12/site-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(
2025-04-04 18:13:09.583190: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M1
2025-04-04 18:13:09.583324: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 8.00 GB
2025-04-04 18:13:09.583404: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 2.67 GB
2025-04-04 18:13:09.583690: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2025-04-04 18:13:09.583733: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, 

In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 390ms/step

2025-04-04 18:13:10.382635: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:117] Plugin optimizer for device_type GPU is enabled.


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 425ms/step


array([[[ 1.98680647e-02,  3.21417190e-02,  3.67486961e-02,
          3.95571105e-02,  4.00328077e-02, -3.64329666e-03,
          2.67087333e-02, -3.12277563e-02,  2.38300674e-02,
         -3.79986987e-02],
        [ 1.98680647e-02,  3.21417190e-02,  3.67486961e-02,
          3.95571105e-02,  4.00328077e-02, -3.64329666e-03,
          2.67087333e-02, -3.12277563e-02,  2.38300674e-02,
         -3.79986987e-02],
        [ 1.98680647e-02,  3.21417190e-02,  3.67486961e-02,
          3.95571105e-02,  4.00328077e-02, -3.64329666e-03,
          2.67087333e-02, -3.12277563e-02,  2.38300674e-02,
         -3.79986987e-02],
        [ 1.98680647e-02,  3.21417190e-02,  3.67486961e-02,
          3.95571105e-02,  4.00328077e-02, -3.64329666e-03,
          2.67087333e-02, -3.12277563e-02,  2.38300674e-02,
         -3.79986987e-02],
        [-4.25399654e-02,  2.38326453e-02,  3.34240086e-02,
         -4.21032310e-02, -2.34877113e-02, -3.56274471e-02,
          3.80483009e-02, -3.41203958e-02,  2.796122

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 6609, 8463, 2300, 7127], dtype=int32)

In [15]:
import numpy as np

model.predict(np.expand_dims(embedded_docs[0], axis=0))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 192ms/step


array([[[ 0.01986806,  0.03214172,  0.0367487 ,  0.03955711,
          0.04003281, -0.0036433 ,  0.02670873, -0.03122776,
          0.02383007, -0.0379987 ],
        [ 0.01986806,  0.03214172,  0.0367487 ,  0.03955711,
          0.04003281, -0.0036433 ,  0.02670873, -0.03122776,
          0.02383007, -0.0379987 ],
        [ 0.01986806,  0.03214172,  0.0367487 ,  0.03955711,
          0.04003281, -0.0036433 ,  0.02670873, -0.03122776,
          0.02383007, -0.0379987 ],
        [ 0.01986806,  0.03214172,  0.0367487 ,  0.03955711,
          0.04003281, -0.0036433 ,  0.02670873, -0.03122776,
          0.02383007, -0.0379987 ],
        [-0.04253997,  0.02383265,  0.03342401, -0.04210323,
         -0.02348771, -0.03562745,  0.0380483 , -0.0341204 ,
          0.02796122, -0.01513491],
        [-0.02327597,  0.02474505,  0.01173908, -0.02503654,
         -0.03064575,  0.00204635,  0.01790665, -0.0233224 ,
          0.03853908, -0.01905617],
        [ 0.0178846 ,  0.01646811,  0.0350616 , -0.0

In [16]:
pip install keras==2.11.0 tensorflow==2.11.0

  Using cached keras-2.11.0-py2.py3-none-any.whl.metadata (1.4 kB)
ERROR: Could not find a version that satisfies the requirement tensorflow==2.11.0 (from versions: 2.16.0rc0, 2.16.1, 2.16.2, 2.17.0rc0, 2.17.0rc1, 2.17.0, 2.17.1, 2.18.0rc0, 2.18.0rc1, 2.18.0rc2, 2.18.0, 2.18.1, 2.19.0rc0, 2.19.0)
ERROR: No matching distribution found for tensorflow==2.11.0
Note: you may need to restart the kernel to use updated packages.


In [17]:
#model.predict(embedded_docs[0])